function Jstr = duffingJacobianStr_ipopt(N)

Jstr = [ones(N), ones(N), zeros(N), zeros(N);...
        ones(N), ones(N), zeros(N), ones(N);...
        ones(N), zeros(N), ones(N), ones(N);...
        zeros(N), zeros(N), ones(N), ones(N)];
Jstr = sparse(Jstr);